apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lolry0207/bit-bite_backend:develop
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: bit-bite-secrets
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: REDIS_URL
              value: "redis://bitbite-redis-service:6379"