apiVersion: v1
kind: Secret
metadata:
  name: bit-bite-secrets
type: Opaque
data:
  DB_PASSWORD: MTIzNA==
  GEMINI_API_KEY: QUlaYVN5QWVSWUdYOU1UdWpKZVRtYldaeUo1d0x6OE0tZTVNMVRF
  MAIL_USERNAME: eXNub2gyMkBzb29rbXl1bmcuYWMua3I=
  MAIL_PASSWORD: dXdtcmFlaW53ZHFxb3BkZA==
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmU=