apiVersion: v1
kind: Secret
metadata:
  name: bit-bite-secrets
type: Opaque
data:
  # PostgreSQL 데이터베이스 암호
  postgres-password: MTIzNA== 
  
  # JWT 토큰 서명 키
  jwt-secret-key: WV91cnN1cGVyX3NlY3VyZV9yYW5kb21fc2VjcmV0 
  
  # Gemini AI API 키
  gemini-api-key: QUl6YVN5QWVSWUdYOU1UdWpKZVRtYldaeWo1d0x6OE0tZTVNMVRF 
  
  # 이메일 발송 계정 사용자 이름
  mail-username: eXNub2gyMkBzb29rbXl1bmcuYWMua3I=
  
  # 이메일 발송 계정 암호
  mail-password: dXdtcmFlaW53ZHFxb3BkZA==