apiVersion: v1
kind: Secret
metadata:
  name: bit-bite-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: MTIzNA==
  DB_NAME: cG9zdGdyZXM=
  REDIS_HOST: Yml0Yml0ZS1yZWRpcy1zZXJ2aWNl
  GEMINI_API_KEY: QUlaYVN5QWVSWUdYOU1UdWpKZVRtYldaeUo1d0x6OE0tZTVNMVRF
  MAIL_USERNAME: eXNub2gyMkBzb29rbXl1bmcuYWMua3I=
  MAIL_PASSWORD: dXdtcmFlaW53ZHFxb3BkZA==
  MAIL_FROM: eXNub2gyMkBzb29rbXl1bmcuYWMua3I=
  MAIL_PORT: NTg3
  MAIL_SERVER: c210cC5nbWFpbC5jb20=
  MAIL_FROM_NAME: Qml0Qml0ZQ==
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmU=