apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-challenge-scheduler
  labels:
    app: scheduler
    job: daily
spec:
  schedule: "00 12 * * 1-5"
  timeZone: "Asia/Seoul"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            component: application
          containers:
            - name: daily-job
              image: ghcr.io/youngseo22/bit-bite_backend:fixv2
              imagePullPolicy: Always
              args: ["python", "/app/scheduler_runner.py", "daily-challenge"]
              envFrom:
                - configMapRef:
                    name: bit-bite-config
                - secretRef:
                    name: bit-bite-secrets
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"