apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-challenge-scheduler
  labels:
    app: scheduler
    job: daily
spec:
  schedule: "00 08 * * 1-5"
  timeZone: "Asia/Seoul"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: daily-job
              image: lolry0207/bit-bite_backend:fix
              imagePullPolicy: Always
              args: ["python", "/app/scheduler_runner.py", "daily-challenge"]
              envFrom:
                - configMapRef:
                    name: bit-bite-config
                - secretRef:
                    name: bit-bite-secrets