apiVersion: batch/v1
kind: CronJob
metadata:
  name: monthly-cleanup-scheduler
  labels:
    app: scheduler
    job: monthly
spec:
  schedule: "0 1 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-job
              image: lolry0207/bit-bite_scheduler:latest
              args: ["python", "/scheduler_main.py", "monthly-cleanup"]
              envFrom:
                - secretRef:
                    name: bit-bite-secrets
              env:
                - name: TZ
                  value: "Asia/Seoul"
                - name: DB_HOST
                  value: postgres-service
                - name: DB_PORT
                  value: "5432"
                - name: REDIS_URL
                  value: "redis://bitbite-redis-service:6379"