apiVersion: batch/v1
kind: CronJob
metadata:
  name: monthly-cleanup-scheduler
  labels:
    app: scheduler
    job: monthly
spec:
  schedule: "0 1 1 * *"
  timeZone: "Asia/Seoul"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-job
              image: lolry0207/bit-bite_backend:fix
              args: ["python", "/app/scheduler_runner.py", "monthly-cleanup"]
              envFrom:
                - configMapRef:
                    name: bit-bite-config
                - secretRef:
                    name: bit-bite-secrets